[tool.flake8]
max-line-length = 88
max-complexity = 10
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv",
    "migrations"
]
count = true
statistics = true
show-source = true
