name: Django Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Flake8 and DjLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # You can change to your preferred version

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 djlint

      - name: Run Flake8 (Python linter)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Run DjLint (Django template linter)
        run: |
          djlint templates/ --check --quiet
