name: Django Security Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 17 * * 5'
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit (Python security linter)
        uses: tj-actions/bandit@v5
        with:
          targets: "."

      - name: Run Safety (Dependency vulnerability scanner)
        run: |
          pip install safety
          safety check --full-report

      - name: Run Django check --deploy
        run: |
          python manage.py check --deploy --fail-level WARNING

      - name: Secret scanning with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml # optional custom config